Feat/security
The-Bugger-Ducks/help-duck-users-microservice pull request #9
Opened 2022-05-05 16:05 UTC by ThHenrique

Implementação da autenticação e autorização usuários utilizando Spring Security e JWT token.

Services Criados:
1. CustomUserDetailsService (Spring Security)
2. User Principal (Spring Security)
3. TokenService (JWT methods)
4. TokenFilter (Spring Security)

Data Transfer Object  (DTO) criados:
1. UserLogin (Objeto de retorno para front)
2. TokenDTO (Objeto de retorno para front)
3. LoginForm (Payload enviado pelo front)

Alterações no SecurityConfig

🚀 pai ta on

2022-05-05 22:18 UTC, GabrielCamargoL requested changes
Muito bom!!! 
Como eu acompanhei o processo contigo, creio que esteja tudo bem com o fluxo e com as boas praticas, para uma estrutura grande que é o spring security.

unica coisa que poderia mudar seria o jwt.expiration e o jwt.secret para simular o ambiente real

```
jwt.expiration= 18000000 (5 horas)
jwt.batata tentar criptografar ou escolher uma chave melhor 
```

2022-05-05 22:34 UTC, ThHenrique commented
@GabrielCamargoL Alteração realizada, criei uma nova secretkey utilizando UUID e coloquei 5h para o token expirar

2022-05-05 22:35 UTC, GabrielCamargoL approved these changes

2022-05-07 01:26 UTC, GabrielCamargoL commented
pode por gentileza implementar a autorização de equipamento? sogrinha :pray:

2022-05-07 01:28 UTC, GabrielCamargoL requested changes
pode por gentileza implementar a autorização de equipamento? sogrinha :pray:

2022-05-09 22:52 UTC, ThHenrique commented
Conforme alinhado hoje 09/05/2022 com @JoaoM-py, @MariaGabrielaReis  e @GabrielCamargoL, não iremos inicialmente implementar AUTORIZAÇÃO nas rotas de equipamento por falta de definição (quem será responsável por realizar as ações de criar, editar, atualizar, ler as informações de equipamentos).

Contudo, usuário deverá estar autenticado no sistema para realizar essas ações.

2022-05-09 22:58 UTC, GabrielCamargoL approved these changes

2022-05-10 11:20 UTC, merged